Repository els0r/goProbe, pull requests merged in 2023-10, with the labels that each got.

#235 [bugfix] Fix --stored-query parameter in goQuery and accept stdin
  cmd/goQuery/cmd/root.go
Labels: bug, feature

#241 [feature] Bump slimcap to alpha v1.0.1 for performance improvements
  go.mod
  go.sum
Labels: performance

#243 [bugfix] Extend logging for capture deadlock detection test
  pkg/capture/capture_test.go
Labels: bug

#232 [feature] Support traffic direction filters
  README.md
  cmd/goQuery/cmd/help.go
  pkg/e2etest/e2e_test.go
  pkg/e2etest/types.go
  pkg/goDB/conditions/node/filter_direction.go
  pkg/goDB/conditions/node/filter_direction_test.go
  pkg/goDB/conditions/node/node.go
  pkg/goDB/conditions/node/node_test.go
  pkg/goDB/conditions/node/parse.go
  pkg/goDB/conditions/node/parse_test.go
  pkg/goDB/engine/aggregate.go
  pkg/goDB/engine/query.go
  pkg/types/hashmap/aggregate.go
  pkg/types/hashmap/hashmap.go
  pkg/types/hashmap/hashmap_test.go
  pkg/types/types.go
Labels: feature

#245 [bugfix][feature] Bump slimcap to release v1.0.1
  go.mod
  go.sum
Labels: bug, feature, performance, dependencies

#246 [feature] Support traffic direction filter autocompletion
  cmd/goquery_completion/common.go
  cmd/goquery_completion/conditional.go
  cmd/goquery_completion/conditional_test.go
  pkg/e2etest/e2e_test.go
  pkg/e2etest/types.go
  pkg/goDB/conditions/node/filter_direction.go
  pkg/goDB/conditions/node/node.go
  pkg/goDB/conditions/node/node_test.go
  pkg/types/types.go
Labels: feature

#240 [feature] API: Add info endpoints for deployment in k8s
  pkg/api/api.go
  pkg/api/client/client.go
  pkg/api/globalquery/server/query.go
  pkg/api/globalquery/spec/openapi.yaml
  pkg/api/globalquery/spec/schemas/_index.yaml
  pkg/api/info.go
  pkg/api/server/server.go
  pkg/api/spec/openapi.yaml
  pkg/api/spec/paths/health.yaml
  pkg/api/spec/paths/info.yaml
  pkg/api/spec/paths/ready.yaml
  pkg/api/spec/schemas/Row.yaml
  pkg/api/spec/schemas/ServiceInfo.yaml
  pkg/api/spec/schemas/_index.yaml
  pkg/api/util.go
  pkg/capture/capture_test.go
Labels: api

#251 [feature] Improve build pipeline speed
  .github/workflows/build-packages.yml
  .github/workflows/ci-pr.yml
  .github/workflows/ci-push.yml
  pkg/capture/capture_test.go
  pkg/e2etest/e2e_test.go
Labels: feature
