Repository els0r/goProbe, pull requests merged in 2023-04, with the labels that each got.

#92 Fix (autogenerated) release artifact paths
  .github/workflows/build-packages.yml
Labels: bug

#100 Make DB workload counter atomic and align type with overall counter
  pkg/goDB/DBWorkManager.go
  pkg/goDB/godb_test.go
Labels: bug

#99 Panic during DB writeout (invalid IPv4 / IPv6 key) due to multiple regressions
  examples/analyze-meta/main.go
  pkg/goDB/db_writer.go
  pkg/goDB/db_writer_test.go
  pkg/goDB/storage/gpfile/gpdir.go
  pkg/goDB/storage/gpfile/gpfile.go
  pkg/types/hashmap/hashmap_test.go
  pkg/types/hashmap/iterator.go
  pkg/types/keyval.go
Labels: bug, critical

#93 Slog POC
  cmd/goConvert/goConvert.go
  cmd/goProbe/goProbe.go
  cmd/goQuery/commands/root.go
  cmd/legacy/main.go
  examples/analyze-meta/main.go
  go.mod
  go.sum
  pkg/api/auth.go
  pkg/api/logger.go
  pkg/capture/capture.go
  pkg/goDB/DBWorkManager.go
  pkg/goDB/engine/benchmarks_test.go
  pkg/goprobe/writeout/handler.go
  pkg/logging/caller-handler.go
  pkg/logging/formatter.go
  pkg/logging/level-split-handler.go
  pkg/logging/logger.go
  pkg/logging/logging.go
  pkg/logging/logging_test.go
Labels: enhancement

#101 [bugfix] Move capture handler call Free() to end of closing state to avoid race condition
  pkg/capture/capture.go
Labels: bug

#103 [feature][security] Unify permissions and add configurability goDB data
  cmd/goConvert/goConvert.go
  cmd/goProbe/config/config.go
  cmd/goProbe/goProbe.go
  cmd/legacy/main.go
  pkg/goDB/db_writer.go
  pkg/goDB/db_writer_test.go
  pkg/goDB/storage/gpfile/gpdir.go
  pkg/goDB/storage/gpfile/gpfile.go
  pkg/goDB/storage/gpfile/gpfile_test.go
  pkg/goDB/storage/gpfile/options.go
  pkg/goprobe/writeout/handler.go
Labels: enhancement, security

#102 [feature][bugfix] Dedicated logging package wrapping log/slog
  cmd/goConvert/goConvert.go
  cmd/goProbe/goProbe.go
  cmd/goQuery/commands/root.go
  cmd/legacy/main.go
  examples/analyze-meta/main.go
  go.mod
  go.sum
  pkg/api/auth.go
  pkg/api/logger.go
  pkg/capture/capture.go
  pkg/goDB/DBWorkManager.go
  pkg/goDB/engine/benchmarks_test.go
  pkg/goDB/info/hostid_default.go
  pkg/goprobe/writeout/handler.go
  pkg/logging/caller-handler.go
  pkg/logging/formatter.go
  pkg/logging/level-split-handler.go
  pkg/logging/logger.go
  pkg/logging/logging.go
  pkg/logging/logging_test.go
Labels: bug, enhancement

#110 [feature] Plain logger for simple CLI logging
  pkg/logging/init.go
  pkg/logging/logger.go
  pkg/logging/logging_test.go
  pkg/logging/plain-handler.go
Labels: feature

#106 [bugfix] Straighten out command-line error handling
  cmd/goQuery/commands/root.go
Labels: bug

#112 [feature] Create PR naming rule (enforcement) GitHub action
  .github/workflows/build-packages.yml
  .github/workflows/pr-naming-rules.yml
Labels: feature
