Repository els0r/goProbe, pull requests merged in 2023-06, with the labels that each got.

#129 [bugfix] Fix race condition when closing mock captures
  go.mod
  go.sum
  pkg/capture/capture.go
  pkg/capture/capture_test.go
  pkg/e2etest/e2e_test.go
Labels: bug

#136 [feature] Only run gin in development mode if log level is debug
  cmd/global-query/cmd/server.go
  cmd/goProbe/goProbe.go
  pkg/api/globalquery/server/server.go
  pkg/api/goprobe/server/server.go
Labels: api

#139 [feature] Reduce memory allocations and increase rotation throughput
  pkg/capture/capture_test.go
  pkg/capture/flow.go
  pkg/capture/rungroup.go
  pkg/e2etest/e2e_test.go
  pkg/goDB/db_writer.go
  pkg/types/keyval.go
Labels: feature, performance

#140 [feature] Update slimcap dependency (issue #50)
  go.mod
  go.sum
Labels: feature, performance
